services:
  - type: web
    name: sikapa-backend
    runtime: node
    buildCommand: bash build.sh
    startCommand: bash start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
    autoDeploy: true
