services:
  - type: web
    name: sikapa-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
    autoDeploy: true
